version: "3.7"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - WEBHOOK_TUNNEL_URL=https://59bf7df2a3d0.ngrok-free.app
      - EDITOR_BASE_URL=https://59bf7df2a3d0.ngrok-free.app
      - N8N_RUNNERS_ENABLED=true
    depends_on:
      - postgres
    volumes:
      - ./n8n_data:/home/node/.n8n

  backup:
    image: postgres:15
    depends_on:
      - postgres
    volumes:
      - ./backups:/backups
    environment:
      - PGPASSWORD=n8npass
    entrypoint: |
      bash -c '
        mkdir -p /backups
        while true; do
          TIMESTAMP=$(date +%F)
          pg_dump -h postgres -U n8n -d n8n > /backups/n8n_backup_$TIMESTAMP.sql
          echo "Backup realizado em: $TIMESTAMP"
          sleep 86400
        done
      '

volumes:
  postgres_data:
  n8n_data:
